# https://developers.cloudflare.com/workers/wrangler/configuration

# https://developers.cloudflare.com/workers/wrangler/configuration/#custom-builds
[build]
command = "pnpm build"

[[d1_databases]]
binding = "DB_Targets"
database_name = "Targets.2024-07-03"
database_id = "d4867df9-9e5f-42ae-b065-69dfaec7d376"